### ISSUE TITLE
設計/モグラの出現確率を出す関数の定義

### ISSUE THREAD

**Issue by hakohumi** [hakohumi/comp.train.whack-a-mole#52]
## 概要

- モグラが出現する関数の定義
  - 説明
    - 残り制限時間と難易度を入力すると、予め難易度と残り時間に合わせたモグラの出現確率を算出し格納したテーブルから、それに応じてtrue（出現）とfalse（未出現）が出力される。

 - 入力
   - 残り制限時間
   - 選択された難易度
 - 出力
   - true（出現） or false（未出現）

## タスク

- 検証内容
  - [x] 実現可能かどうか
  - [x] 仕様通りの動作をしているか
    - [x] 出現数は想定どおりか
    - [x] 出現数の増加が実感できるか

**Comment by tomohirosasaki-erii** [comment]
モグラの出現時間(出現中と撃退)の時間も考慮する必要あり。想定より出現数が少なかった。

**Comment by tomohirosasaki-erii** [comment]
制限時間の60秒からモグラの総出現時間(モグラの想定出現数×モグラ1匹の出現時間)を減算し、この時間当たりの出現率を使用したところ、おおむね想定通りの出現数になった。

**Comment by tomohirosasaki-erii** [comment]
4匹同時に出現させて、想定通りの出現数になるか試す。

**Comment by tomohirosasaki-erii** [comment]
4匹同時にモグラを出現させたところ、想定出現数と多少の差はあるが、おおむね期待通りの出現数となった。
しかし、ゲームのバランスを考えると難しく感じたため、総出現数を調整する必要がある。
