### ISSUE TITLE
調査/チャタ取り確認

### ISSUE THREAD

**Issue by hakohumi** [hakohumi/comp.train.whack-a-mole#57]
## 概要

目的
- タイマの間隔を短く設定した場合に、スイッチのチャタ取りできるか
- 一般的なゲームのコントローラ入力の間隔が100Hz(10ms)らしい
- 今回は、10ms ~ 20msで検討する
- チャタ取りは3回 (キッチンタイマで使ったものそのまま）

変更条件
- タイマを5msにし、チャタ取り間隔はやめる

入力
- スイッチ

出力
- LCD or LED

## タスク

- [ ] チャタリングが発生していないかを確認する。

## 参考資料

#54 

## 完了条件

- チャタ取りが10msと同じような感覚でできているか

**Comment by tomohirosasaki-erii** [comment]
クロックを16MHz、タイマ間隔を5msでSW入力時のチャタリングを確認。正常に動作した。
